version: '3'

services:
  app: &app-base
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
  worker:
    <<: *app-base
    build: .
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:5-alpine
    command: [redis-server, --loglevel, notice]
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "6379:6379"
volumes:
  bundle:
  mysql_data:
  redis_data:
